---
- name: Bootstrap common prerequisites
  hosts: all
  become: true
  vars_files:
    - vault.yml
  roles:
    - common

- name: Initialize Swarm on master
  hosts: master
  become: true
  vars_files:
    - vault.yml
  roles:
    - swarm_init

- name: Join workers to Swarm
  hosts: workers
  become: true
  vars_files:
    - vault.yml
  roles:
    - swarm_join

- name: Deploy DB stack on master
  hosts: master
  become: true
  vars_files:
    - vault.yml
  roles:
    - db_stack

- name: Deploy WordPress stack on Swarm
  hosts: master
  become: true
  vars_files:
    - vault.yml
  roles:
    - wordpress_stack

