# playbook_setup_swarm.yml 또는 별도의 firewall_setup.yml 파일에 포함
# Worker 노드용 Firewalld 설정

- name: Worker node firewalld configuration for Docker Swarm and services
  hosts: all # 워커 노드 그룹에만 적용
  become: yes
  tasks:
    - name: Ensure firewalld service is running
      ansible.builtin.systemd:
        name: firewalld
        state: started
        enabled: yes

    # 1. SSH (관리용)
    - name: Allow SSH port (22/tcp)
      ansible.posix.firewalld:
        port: 22/tcp
        zone: public
        state: enabled
        permanent: true
      notify: Reload firewalld

    # 2. Docker Swarm Overlay Network 통신 포트 (모든 Swarm 노드에 필수)
    - name: Allow Docker Swarm overlay network ports (7946 tcp/udp, 4789/udp)
      ansible.posix.firewalld:
        port: "{{ item.port }}/{{ item.protocol }}"
        zone: public
        state: enabled
        permanent: true
      loop:
        - { port: 7946, protocol: 'tcp' }
        - { port: 7946, protocol: 'udp' }
        - { port: 4789, protocol: 'udp' }
      notify: Reload firewalld

    # 3. 웹 서비스 포트 (워드프레스 웹 트래픽)
    #    워커 노드도 Ingress 트래픽을 받아 워드프레스 컨테이너로 라우팅할 수 있으므로 80/tcp를 엽니다.
    - name: Allow HTTP (80/tcp) for web access
      ansible.posix.firewalld:
        port: 80/tcp
        zone: public
        state: enabled
        permanent: true
      notify: Reload firewalld
    
    # 4. Docker가 생성하는 브릿지 인터페이스를 trusted zone에 추가 (가장 중요!)
    - name: Add docker_gwbridge to trusted zone
      ansible.posix.firewalld:
        interface: docker_gwbridge
        zone: trusted
        state: enabled
        permanent: true
      notify: Reload firewalld

    - name: Add docker0 to trusted zone
      ansible.posix.firewalld:
        interface: docker0
        zone: trusted
        state: enabled
        permanent: true
      notify: Reload firewalld

  handlers:
    - name: Reload firewalld
      ansible.builtin.systemd:
        name: firewalld
        state: reloaded
      listen: "Reload firewalld" # notify의 이름과 동일하게 설정
