---
- name: Generate SSH key on controller node using ssh-keygen command
  hosts: localhost # 이 태스크는 Ansible 컨트롤 노드 자체에서 실행됩니다.
  connection: local # 로컬 머신에서 실행함을 의미합니다.
  become: no       # SSH 키는 보통 현재 사용자 계정에서 생성됩니다.

  tasks:
    - name: Check if private key ~/.ssh/id_rsa already exists
      ansible.builtin.stat:
        path: "~/.ssh/id_rsa"
      register: id_rsa_status

    - name: Generate SSH key pair if it does not exist
      ansible.builtin.shell: |
        ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N ""
        chmod 600 ~/.ssh/id_rsa
        chmod 644 ~/.ssh/id_rsa.pub
      # -N "" : passphrase 없이 키를 생성합니다. 자동화를 위해 주로 사용됩니다.
      # -f ~/.ssh/id_rsa : 생성될 개인 키의 경로와 이름을 지정합니다.
      when: not id_rsa_status.stat.exists # 키가 존재하지 않을 때만 이 명령어를 실행합니다 (멱등성 확보)
      register: keygen_output
      changed_when: keygen_output.rc == 0 # 명령어 실행이 성공하면 changed 상태로 표시

    - name: Display status of key generation
      ansible.builtin.debug:
        msg: "SSH key generation for ~/.ssh/id_rsa completed or key already existed."
