# roles/docker_swarm_setup/tasks/main.yml
---
- name: Run master node initialization tasks
  ansible.builtin.include_tasks: master_init.yml
  when: inventory_hostname in groups['master'] # 현재 호스트가 'master' 그룹에 속하면 실행

- name: Run worker node joining tasks
  ansible.builtin.include_tasks: worker_join.yml
  when: inventory_hostname in groups['worker'] # 현재 호스트가 'worker' 그룹에 속하면 실행
