---
- name: Ensure /opt/wordpress directory exists
  file:
    path: /opt/wordpress
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Deploy DB stack
  template:
    src: db-compose.yml.j2
    dest: /opt/wordpress/db-compose.yml
    mode: '0644'

- name: Start DB stack
  command: docker stack deploy -c /opt/wordpress/db-compose.yml db_stack
  args:
    chdir: /opt/wordpress

