# roles/docker_install/tasks/main.yml
---
- name: Update dnf cache and install essential packages
  dnf:
    name: dnf-utils
    state: present
    update_cache: yes
  tags: install_docker

- name: Add Docker GPG key
  rpm_key:
    state: present
    key: https://download.docker.com/linux/centos/gpg
  tags: install_docker

- name: Add Docker YUM repository
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: '0644'
  tags: install_docker

- name: Install Docker Engine, CLI, and Containerd
  dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: yes
  tags: install_docker

- name: Start Docker service and enable on boot
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes
  tags: install_docker

- name: Add remote user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}" # Ansible이 원격 접속 시 사용하는 사용자 이름입니다.
    groups: docker
    append: yes
  notify:
    - Request SSH session re-login after adding to Docker group
  tags: install_docker
- name: Open Docker Swarm ports on master node
  ansible.posix.firewalld:
    zone: public
    port: "{{ item.port }}/{{ item.protocol }}"
    permanent: yes
    state: enabled
  loop: "{{ swarm_ports_to_open }}"
  notify:
    - Reload firewalld
    - Reload docker

