# roles/docker_install/tasks/main.yml
---
- name: Install yum-utils
  ansible.builtin.dnf:
    name: yum-utils
    state: present
  tags: docker_install

- name: Add Docker repo
  ansible.builtin.command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo
  tags: docker_install

- name: Install Docker CE packages
  ansible.builtin.dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true
  tags: docker_install

- name: Start and enable Docker service
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes
  tags: docker_install

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  tags: docker_install
  # 이 태스크는 현재 사용자(ansible_user)가 docker 명령을 sudo 없이 사용할 수 있게 합니다.
  # 변경 사항을 적용하려면 현재 사용자의 쉘을 다시 로드하거나 재로그인해야 할 수 있습니다.
