# roles/docker_install/handlers/main.yml
---
- name: Request SSH session re-login after adding to Docker group
  ansible.builtin.debug:
    msg: |
      ******************************************************************
      ** [ACTION REQUIRED] Please re-login to your SSH session       **
      ** (or run `newgrp docker`) on the managed node(s) to apply    **
      ** Docker group changes for user '{{ ansible_user }}'.         **
      ******************************************************************
- name: Reload firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: reloaded
    daemon_reload: yes # firewalld service를 리로드할 때 daemon-reload도 함께 수행하여 변경사>항 즉시 적용
- name: Reload docker
  ansible.builtin.systemd:
    name: docker
    state: restarted
